// Complete Catholic Bible Data (73 Books)
window.BIBLE_BOOKS = {
    OT: [
        { id: "Genesis", en: "Genesis", ta: "தொடக்க நூல்", chapters: 50 },
        { id: "Exodus", en: "Exodus", ta: "விடுதலைப் பயணம்", chapters: 40 },
        { id: "Leviticus", en: "Leviticus", ta: "லேவியர்", chapters: 27 },
        { id: "Numbers", en: "Numbers", ta: "எண்ணிக்கை", chapters: 36 },
        { id: "Deuteronomy", en: "Deuteronomy", ta: "இணைச் சட்டம்", chapters: 34 },
        { id: "Joshua", en: "Joshua", ta: "யோசுவா", chapters: 24 },
        { id: "Judges", en: "Judges", ta: "நீதித் தலைவர்கள்", chapters: 21 },
        { id: "Ruth", en: "Ruth", ta: "ரூத்து", chapters: 4 },
        { id: "1Samuel", en: "1 Samuel", ta: "1 சாமுவேல்", chapters: 31 },
        { id: "2Samuel", en: "2 Samuel", ta: "2 சாமுவேல்", chapters: 24 },
        { id: "1Kings", en: "1 Kings", ta: "1 அரசர்கள்", chapters: 22 },
        { id: "2Kings", en: "2 Kings", ta: "2 அரசர்கள்", chapters: 25 },
        { id: "1Chronicles", en: "1 Chronicles", ta: "1 குறிப்பேடு", chapters: 29 },
        { id: "2Chronicles", en: "2 Chronicles", ta: "2 குறிப்பேடு", chapters: 36 },
        { id: "Ezra", en: "Ezra", ta: "எஸ்ரா", chapters: 10 },
        { id: "Nehemiah", en: "Nehemiah", ta: "நெகேமியா", chapters: 13 },
        { id: "Tobit", en: "Tobit", ta: "தோபித்து", chapters: 14 },
        { id: "Judith", en: "Judith", ta: "யூதித்து", chapters: 16 },
        { id: "Esther", en: "Esther", ta: "எஸ்தர்", chapters: 10 },
        { id: "1Maccabees", en: "1 Maccabees", ta: "1 மக்கபேயர்", chapters: 16 },
        { id: "2Maccabees", en: "2 Maccabees", ta: "2 மக்கபேயர்", chapters: 15 },
        { id: "Job", en: "Job", ta: "யோபு", chapters: 42 },
        { id: "Psalms", en: "Psalms", ta: "திருப்பாடல்கள்", chapters: 150 },
        { id: "Proverbs", en: "Proverbs", ta: "நீதிமொழிகள்", chapters: 31 },
        { id: "Ecclesiastes", en: "Ecclesiastes", ta: "சபை உரையாளர்", chapters: 12 },
        { id: "SongOfSolomon", en: "Song of Solomon", ta: "இனிமைமிகு பாடல்", chapters: 8 },
        { id: "Wisdom", en: "Wisdom", ta: "சாலமோனின் ஞானம்", chapters: 19 },
        { id: "Sirach", en: "Sirach", ta: "சீராக்", chapters: 51 },
        { id: "Isaiah", en: "Isaiah", ta: "எசாயா", chapters: 66 },
        { id: "Jeremiah", en: "Jeremiah", ta: "எரேமியா", chapters: 52 },
        { id: "Lamentations", en: "Lamentations", ta: "புலம்பல்", chapters: 5 },
        { id: "Baruch", en: "Baruch", ta: "பாரூக்கு", chapters: 6 },
        { id: "Ezekiel", en: "Ezekiel", ta: "எசேக்கியேல்", chapters: 48 },
        { id: "Daniel", en: "Daniel", ta: "தானியேல்", chapters: 14 },
        { id: "Hosea", en: "Hosea", ta: "ஓசேயா", chapters: 14 },
        { id: "Joel", en: "Joel", ta: "யோவேல்", chapters: 3 },
        { id: "Amos", en: "Amos", ta: "ஆமோஸ்", chapters: 9 },
        { id: "Obadiah", en: "Obadiah", ta: "ஒபதியா", chapters: 1 },
        { id: "Jonah", en: "Jonah", ta: "யோனா", chapters: 4 },
        { id: "Micah", en: "Micah", ta: "மீக்கா", chapters: 7 },
        { id: "Nahum", en: "Nahum", ta: "நாகூம்", chapters: 3 },
        { id: "Habakkuk", en: "Habakkuk", ta: "அபக்கூக்கு", chapters: 3 },
        { id: "Zephaniah", en: "Zephaniah", ta: "செப்பனியா", chapters: 3 },
        { id: "Haggai", en: "Haggai", ta: "ஆகாய்", chapters: 2 },
        { id: "Zechariah", en: "Zechariah", ta: "செக்கரியா", chapters: 14 },
        { id: "Malachi", en: "Malachi", ta: "மலாக்கி", chapters: 3 }
    ],
    NT: [
        { id: "Matthew", en: "Matthew", ta: "மத்தேயு", chapters: 28 },
        { id: "Mark", en: "Mark", ta: "மாற்கு", chapters: 16 },
        { id: "Luke", en: "Luke", ta: "லூக்கா", chapters: 24 },
        { id: "John", en: "John", ta: "யோவான்", chapters: 21 },
        { id: "Acts", en: "Acts", ta: "திருத்தூதர் பணிகள்", chapters: 28 },
        { id: "Romans", en: "Romans", ta: "உரோமையர்", chapters: 16 },
        { id: "1Corinthians", en: "1 Corinthians", ta: "1 கொரிந்தியர்", chapters: 16 },
        { id: "2Corinthians", en: "2 Corinthians", ta: "2 கொரிந்தியர்", chapters: 13 },
        { id: "Galatians", en: "Galatians", ta: "கலாத்தியர்", chapters: 6 },
        { id: "Ephesians", en: "Ephesians", ta: "எபேசியர்", chapters: 6 },
        { id: "Philippians", en: "Philippians", ta: "பிலிப்பியர்", chapters: 4 },
        { id: "Colossians", en: "Colossians", ta: "கொலோசையர்", chapters: 4 },
        { id: "1Thessalonians", en: "1 Thessalonians", ta: "1 தெசலோனிக்கேயர்", chapters: 5 },
        { id: "2Thessalonians", en: "2 Thessalonians", ta: "2 தெசலோனிக்கேயர்", chapters: 3 },
        { id: "1Timothy", en: "1 Timothy", ta: "1 திமொத்தேயு", chapters: 6 },
        { id: "2Timothy", en: "2 Timothy", ta: "2 திமொத்தேயு", chapters: 4 },
        { id: "Titus", en: "Titus", ta: "தீத்து", chapters: 3 },
        { id: "Philemon", en: "Philemon", ta: "பிலமோன்", chapters: 1 },
        { id: "Hebrews", en: "Hebrews", ta: "எபிரேயர்", chapters: 13 },
        { id: "James", en: "James", ta: "யாக்கோபு", chapters: 5 },
        { id: "1Peter", en: "1 Peter", ta: "1 பேதுரு", chapters: 5 },
        { id: "2Peter", en: "2 Peter", ta: "2 பேதுரு", chapters: 3 },
        { id: "1John", en: "1 John", ta: "1 யோவான்", chapters: 5 },
        { id: "2John", en: "2 John", ta: "2 யோவான்", chapters: 1 },
        { id: "3John", en: "3 John", ta: "3 யோவான்", chapters: 1 },
        { id: "Jude", en: "Jude", ta: "யூதா", chapters: 1 },
        { id: "Revelation", en: "Revelation", ta: "திருவெளிப்பாடு", chapters: 22 }
    ]
};
