name: Deploy to Firebase Hosting on Branch Push

on:
  push:
    branches:
      - main
      - DEV

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 🛠️ DEV BRANCH -> Deploy to stacpaganurdev.web.app
      - name: Deploy to Development Environment
        if: github.ref == 'refs/heads/DEV'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_STACPAGANUR }}
          projectId: stacpaganur
          site: stacpaganurdev
          channelId: live

      # 🚀 MAIN BRANCH -> Deploy to stacpaganur.web.app (Live Production)
      - name: Deploy to Live Production
        if: github.ref == 'refs/heads/main'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_STACPAGANUR }}
          projectId: stacpaganur
          site: stacpaganur
          channelId: live
